import { join } from 'node:path';
import { writeFileSync, cpSync, mkdirSync, existsSync } from 'node:fs';
import type { Renderer } from './renderer.interface.js';
import type { FormatType, IntermediateSkill, SkillDirectory, DirectoryConversionResult } from '../core/types.js';

/**
 * Renders IntermediateSkill to .cursorrules format (Cursor IDE).
 *
 * .cursorrules is a plain text file with no frontmatter.
 * Metadata is stored as # comments at the top of the file.
 *
 * Directory mode: copies scripts/assets alongside the .cursorrules file.
 */
export class CursorRulesRenderer implements Renderer {
  readonly format: FormatType = '.cursorrules';
  readonly extension = '.cursorrules';

  render(skill: IntermediateSkill): string {
    const parts: string[] = [];

    parts.push(`# ${skill.name}`);
    if (skill.description) {
      parts.push(`# ${skill.description}`);
    }
    parts.push(`# Generated by TransSkill from ${skill.metadata.sourceFormat}`);
    parts.push('');

    parts.push(skill.instructions || '');

    return parts.join('\n').trim() + '\n';
  }

  renderDirectory(
    skillDir: SkillDirectory,
    skill: IntermediateSkill,
    outputPath: string,
  ): DirectoryConversionResult {
    const copied: string[] = [];
    const skipped: string[] = [];

    const rulesPath = join(outputPath, `${skillDir.name}.cursorrules`);
    writeFileSync(rulesPath, this.render(skill), 'utf-8');

    if (skillDir.scriptsDir) {
      const target = join(outputPath, 'scripts');
      if (!existsSync(target)) {
        mkdirSync(target, { recursive: true });
      }
      try {
        cpSync(skillDir.scriptsDir, target, { recursive: true });
        copied.push(target);
      } catch {
        skipped.push(skillDir.scriptsDir);
      }
    }

    if (skillDir.assetsDir) {
      const target = join(outputPath, 'assets');
      try {
        cpSync(skillDir.assetsDir, target, { recursive: true });
        copied.push(target);
      } catch {
        skipped.push(skillDir.assetsDir);
      }
    }

    return {
      skillName: skill.name,
      mainOutput: rulesPath,
      copiedFiles: copied,
      skippedFiles: skipped,
    };
  }
}
